---
apiVersion: v1
kind: Service
metadata:
  name: admin-http
  namespace: pay
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: admin-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-http
  namespace: pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-http
  template:
    metadata:
      labels:
        app: admin-http
    spec:
      containers:
        - image: admin-http
          name: admin-http
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: nacos-secret
          volumeMounts:
            - mountPath: /app/storage/logs
              name: log
      volumes:
        - emptyDir: {}
          name: log
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: admin-http
  namespace: pay
spec:
  ingressClassName: higress
  rules:
    - host: api.dev
      http:
        paths:
          - backend:
              service:
                name: admin-http
                port:
                  name: http
            path: /admin
            pathType: Prefix
  tls:
    - hosts:
        - admin.dev
